### PR TITLE
#42 Plain Language - All Content

### PR DESCRIPTION
**Pull request by inclusiveThinking**
#42 Plain Language - All Content from COGA. SC Manager is Jim Smith

### CODE REVIEW

**Comment by michael-n-cooper** [comment]
I edited this pull request but the edits wound up in the branch pr/105 rather than a modification of this pull request, so this may need to be closed and a new pull request created.

**Comment by inclusiveThinking** [comment]
Hi Michael. I am not the SC Manager on this but glad to help. Is there an actionable item I need to engage in on my part?

**Comment by lseeman** [comment]
Is this sorted out? SHould we redo the pull request?

All the best

Lisa Seeman

LinkedIn, Twitter





---- On Thu, 09 Feb 2017 01:52:43 +0200 michael-n-cooper&lt;notifications@github.com&gt; wrote ---- 

I edited this pull request but the edits wound up in the branch pr/105 rather than a modification of this pull request, so this may need to be closed and a new pull request created.

**Comment by inclusiveThinking** [comment]
I have not made any modification or reinitiated a new PR. I left comments
offering to help in the 2 others that had this problem but have not heard
an update.

**Comment by inclusiveThinking** [comment]
This Pull Request request was initiated for SC Manager Jim Smith (I do not see him listed as a repo member so including @lseeman). I mistakenly used the process and formatting for submitting Issues. Please let me know if this needs to be closed and if a new Pull Request needs to be opened using the SC format.

**Comment by inclusiveThinking** [comment]
Closing and reinitiating

**Pull request closed without merging**
