### PR TITLE
#36 Clear Controls

### PR DESCRIPTION
**Pull request by inclusiveThinking**
#36 Clear Controls from the COGA Task Force

### CODE REVIEW

**Comment by awkawk** [comment]
@inclusiveThinking @lseeman This SC indicated in the issue that it would be under principle 3 but didn't indicate the guideline. Where does this belong?

**Comment by inclusiveThinking** [comment]
@awkawk,  @NeilMilliken is the SC Manager for this. I am helping members of the TF who have difficulties with HTML or GitHub but don't own the content. I have included @NeilMilliken here as the SC Manager.

**Comment by inclusiveThinking** [comment]
@joshueoconnor this should be assigned to @NeilMilliken as the SC manager. Same with #55

**Comment by lseeman** [comment]
yes, we think it is under 3.1 if we change the word  "text" to "content".

**Comment by NeilMilliken** [comment]
I agree with Lisa.

**Comment by inclusiveThinking** [comment]
@NeilMilliken @lseeman @awkawk This PR was opened as an Issue but was meant to be a PR. I would recommend closing this and reinitiating. I would recommend including comments above in the new PR

**Comment by awkawk** [comment]
Old Pull request, overcome by events as WG didn't adopt this SC in this form.

**Pull request closed without merging**
