### PR TITLE
Resolve issue 506

### PR DESCRIPTION
**Pull request by DavidMacDonald**
replaced "control that triggers it" with "triggering mechanism" from issue #506

### CODE REVIEW

**Comment by awkawk** [comment]
@DavidMacDonald this PR should only have changes related to the Change of Content file, but it has a bunch more. Can you separate these out?

**Comment by DavidMacDonald** [comment]
@awkawk Actually the edit is exactly what it says it is
https://github.com/w3c/wcag21/pull/521/commits/513c371cbcc803e31daa52ca73a428bc9de5cc91
Now other requests are part of that branch. Not sure what to do about that.

**Comment by awkawk** [comment]
Yes, that commit is what you said, and to be clear I wasn't saying that it wasn't but it is now part of a larger pull request that is not just that edit. Can you target the pull request for that edit to Master instead of to the branch that we are using for the understanding content?

**Comment by DavidMacDonald** [comment]
@awkawk done.

**Comment by steverep** [comment]
@awkawk, it appears David branched this change off of the user-interface-component-minimum branch instead of master, so it has some changes from Glenda as well.

@DavidMacDonald, the quickest way to fix this is just to delete this branch and pull request and create another, making sure to branch off of master.

**Comment by DavidMacDonald** [comment]
I've opened a new branch and pull request. This branch seems to not want to be deleted so I've left it for now.

**Pull request closed without merging**
